/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RotuloImgCalculator = new javax.swing.JLabel();
        RotuloLogin = new javax.swing.JLabel();
        RotuloSenha = new javax.swing.JLabel();
        CampoLogin = new javax.swing.JTextField();
        BotaoLogar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        RotuloTitulo = new javax.swing.JLabel();
        CampoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        RotuloImgCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Apps-Calc-icon.png"))); // NOI18N

        RotuloLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RotuloLogin.setText("Usuario");

        RotuloSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RotuloSenha.setText("Senha");

        CampoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoLoginMouseClicked(evt);
            }
        });

        BotaoLogar.setBackground(new java.awt.Color(255, 255, 153));
        BotaoLogar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoLogar.setText("Login");
        BotaoLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogarActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(255, 255, 153));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        RotuloTitulo.setBackground(new java.awt.Color(255, 255, 102));
        RotuloTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RotuloTitulo.setText("Painel de Login");

        CampoSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RotuloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RotuloSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RotuloTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoLogin)
                            .addComponent(CampoSenha)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotaoLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(BotaoCancelar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(RotuloImgCalculator)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RotuloTitulo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RotuloLogin)
                            .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RotuloSenha)
                            .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RotuloImgCalculator))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogarActionPerformed

        if(CampoLogin.getText().equals("admin") && CampoSenha.getText().equals("admin")){
            try{
        File f = new File("C:\\Users\\Windows\\Desktop\\Engenharia da Computação\\2022.1\\"
        + "Programação orientada a objetos\\Projeto\\Projeto\\src\\Audios\\LoginEfetuadoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
            
            JOptionPane.showMessageDialog(null,"Sucess");
           new TelaEdicao().setVisible(true); 
           this.dispose();
       }else{
             try{
        File f = new File("C:\\Users\\Windows\\Desktop\\Engenharia da Computação\\2022.1\\"
        + "Programação orientada a objetos\\Projeto\\Projeto\\src\\Audios\\LoginIncorretoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
           JOptionPane.showMessageDialog(null,"Erro");
           
       }
    }//GEN-LAST:event_BotaoLogarActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
         try{
        File f = new File("C:\\Users\\Windows\\Desktop\\Engenharia da Computação\\2022.1\\"
        + "Programação orientada a objetos\\Projeto\\Projeto\\src\\Audios\\CancelarAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }    
        this.dispose();
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void CampoSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoSenhaMouseClicked
        try{
        File f = new File("C:\\Users\\Windows\\Desktop\\Engenharia da Computação\\2022.1\\"
        + "Programação orientada a objetos\\Projeto\\Projeto\\src\\Audios\\SenhaAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_CampoSenhaMouseClicked

    private void CampoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoLoginMouseClicked
        try{
        File f = new File("C:\\Users\\Windows\\Desktop\\Engenharia da Computação\\2022.1\\"
        + "Programação orientada a objetos\\Projeto\\Projeto\\src\\Audios\\UsuarioAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_CampoLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoLogar;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel RotuloImgCalculator;
    private javax.swing.JLabel RotuloLogin;
    private javax.swing.JLabel RotuloSenha;
    private javax.swing.JLabel RotuloTitulo;
    // End of variables declaration//GEN-END:variables
}
