
package projeto;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;



public class TelaEdicao extends javax.swing.JFrame {

   float num1,num2,res;
    
    
  
   
    public TelaEdicao() {
         
        initComponents();//inicia os componentes  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RotuloCalculadora = new javax.swing.JLabel();
        RotuloValor1 = new javax.swing.JLabel();
        RotuloValor2 = new javax.swing.JLabel();
        RotuloResultado = new javax.swing.JLabel();
        CampoValor1 = new javax.swing.JTextField();
        CampoValor2 = new javax.swing.JTextField();
        CampoResultado = new javax.swing.JTextField();
        BotaoAdicao = new javax.swing.JButton();
        BotaoSubtracao = new javax.swing.JButton();
        BotaoMultiplicacao = new javax.swing.JButton();
        BotaoDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RotuloCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RotuloCalculadora.setText("Calculadora");

        RotuloValor1.setText("Valor 1");

        RotuloValor2.setText("Valor 2");

        RotuloResultado.setText("Resultado");

        CampoValor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoValor1MouseClicked(evt);
            }
        });

        CampoValor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoValor2MouseClicked(evt);
            }
        });

        CampoResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoResultadoMouseClicked(evt);
            }
        });

        BotaoAdicao.setText("Adição");
        BotaoAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicaoActionPerformed(evt);
            }
        });

        BotaoSubtracao.setText("Subtração");
        BotaoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSubtracaoActionPerformed(evt);
            }
        });

        BotaoMultiplicacao.setText("Multiplicação");
        BotaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMultiplicacaoActionPerformed(evt);
            }
        });

        BotaoDivisao.setText("Divisão");
        BotaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(RotuloValor1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CampoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(RotuloCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(RotuloValor2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(CampoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(RotuloResultado))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoAdicao)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSubtracao)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoMultiplicacao)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoDivisao)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(RotuloCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RotuloValor1)
                    .addComponent(RotuloValor2)
                    .addComponent(RotuloResultado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAdicao)
                    .addComponent(BotaoSubtracao)
                    .addComponent(BotaoMultiplicacao)
                    .addComponent(BotaoDivisao))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicaoActionPerformed
        Adicao soma = new Adicao();
        num1=Integer.parseInt(CampoValor1.getText());
        num2=Integer.parseInt(CampoValor2.getText());
        CampoResultado.setText(String.valueOf(soma.calcular(num1,num2)));
         try{
        File f = new File("src\\Audios\\AdicaoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
        
    }//GEN-LAST:event_BotaoAdicaoActionPerformed

    private void BotaoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSubtracaoActionPerformed
       Subtracao sub = new Subtracao();
        num1=Integer.parseInt(CampoValor1.getText());
        num2=Integer.parseInt(CampoValor2.getText());
        CampoResultado.setText(String.valueOf(sub.calcular(num1,num2)));
         try{
        File f = new File("src\\Audios\\SubtracaoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_BotaoSubtracaoActionPerformed

    private void BotaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMultiplicacaoActionPerformed
      Multiplicacao mult = new Multiplicacao();
        num1=Integer.parseInt(CampoValor1.getText());
        num2=Integer.parseInt(CampoValor2.getText());
        CampoResultado.setText(String.valueOf(mult.calcular(num1,num2)));
        
         try{
        File f = new File("src\\Audios\\MultiplicacaoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_BotaoMultiplicacaoActionPerformed

    private void BotaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDivisaoActionPerformed
        
        Divisao div = new Divisao();
        num1=Integer.parseInt(CampoValor1.getText());
        num2=Integer.parseInt(CampoValor2.getText());
        try{
        res=div.calcular(num1,num2);        
       }
        catch(ArithmeticException obj){
        JOptionPane.showMessageDialog(null,"Erro divisao por zero");
        this.dispose();
        }
       CampoResultado.setText(String.valueOf(res));
       
        try{
        File f = new File("src\\Audios\\DivisaoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
      
    }//GEN-LAST:event_BotaoDivisaoActionPerformed

    private void CampoValor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoValor1MouseClicked
         try{
        File f = new File("src\\Audios\\CampoNumero1Audio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_CampoValor1MouseClicked

    private void CampoValor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoValor2MouseClicked
         try{
        File f = new File("src\\Audios\\CampoNumero2Audio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_CampoValor2MouseClicked

    private void CampoResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoResultadoMouseClicked
        try{
        File f = new File("src\\Audios\\CampoResultadoAudio.wav");
        Clip clip = AudioSystem.getClip();
        AudioInputStream ais = AudioSystem.getAudioInputStream(f);
        clip.open(ais);
        clip.start();  
    }catch(Exception exception){
        System.out.println("Falha ao iniciar arquivo");
    }
    }//GEN-LAST:event_CampoResultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEdicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicao;
    private javax.swing.JButton BotaoDivisao;
    private javax.swing.JButton BotaoMultiplicacao;
    private javax.swing.JButton BotaoSubtracao;
    private javax.swing.JTextField CampoResultado;
    private javax.swing.JTextField CampoValor1;
    private javax.swing.JTextField CampoValor2;
    private javax.swing.JLabel RotuloCalculadora;
    private javax.swing.JLabel RotuloResultado;
    private javax.swing.JLabel RotuloValor1;
    private javax.swing.JLabel RotuloValor2;
    // End of variables declaration//GEN-END:variables
}
